# Generated by Django 5.1 on 2024-08-19 08:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chat', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='movieroom',
            name='members',
            field=models.ManyToManyField(related_name='movie_rooms', to=settings.AUTH_USER_MODEL),
        ),
    ]
